### ISSUE TITLE
Probleme to generate with twig [http, https].

### ISSUE THREAD

**Issue by xorgxx** [endroid/qr-code-bundle#13]
Hi,
this work : 
```
<img src="http://www.xxxxxx.ap2/app_dev.php/fr/qrcode/http://www.xxxxxx.ap2/app_dev.php/fr/xxx/nfctag/secure/eac9508a7f6d0f5e8cd517b91deb903d.png">
```

but if i generate in HTTPS das not work : 
```
<img src="https://www.xxxxxx.ap2/app_dev.php/fr/qrcode/https://www.xxxxxx.ap2/app_dev.php/fr/xxx/nfctag/secure/eac9508a7f6d0f5e8cd517b91deb903d.png">
```

i generate url in controller : 
```
$url        = $this->generateUrl( 'nfc_secure_index',array('machash' => $yneTag->getMachash()), UrlGeneratorInterface::ABSOLUTE_URL );
```    

in twig : 
`<img src="{{ qrcode_url( url ) }}"/>`

here is config : 
```
endroid_qr_code:
    writer: 'png'
    size: 140           # 300  150
    margin: 10
    foreground_color: { r: 0, g: 51, b: 102 }  # 255, 204, 0   0, 51, 102
    background_color: { r: 255, g: 255, b: 255 }
    error_correction_level: quartile # low, medium, quartile or high
    encoding: UTF-8
    label: Yne life
    label_font_size: 14   # 300 13
    label_alignment: center # left, center or right
    label_margin: { b: 20 }
    logo_path: '%kernel.root_dir%/../web/bundles/corestyle/images/xxxxx/commons/logodark@300.jpg'
    logo_width: 55    # 150 55
    validate_result: true # checks if the result is readable
```

can you help ?
Thank.

Ps: SF3.316, qrcode 2.4.0, Windows 10 64, PHP 5.6

**Comment by endroid** [comment]
Hi @xorgxx what error do you get when you open the https url to your image directly in the browser?

**Comment by xorgxx** [comment]
get no error just dont have png to read. if i open be http no probleme Qrcode there, but bu https i get nathink. (no png)

```
Built-in validation reader read "" instead of "https://www.xxxxx.ap2/app_dev.php/fr/xxxx/nfctag/secure/eac9508a7f6d0f5e8cd517b91deb903d".
Adjust your parameters to increase readability or disable built-in validation.


in vendor\endroid\qrcode\src\Writer\PngWriter.php (line 53)

            $string = $this->imageToString($image);
            if ($qrCode->getValidateResult()) {
                $reader = new QrReader($string, QrReader::SOURCE_TYPE_BLOB);
                if ($reader->text() !== $qrCode->getText()) {
                    throw new ValidationException(
                        'Built-in validation reader read "'.$reader->text().'" instead of "'.$qrCode->getText().'".
                         Adjust your parameters to increase readability or disable built-in validation.');
                }
            }
```

**Comment by xorgxx** [comment]
Ok i got the probleme : 

````
endroid_qr_code:
    writer: 'png'
    size: 160           # 300  150   <---------------- here it was 140
    margin: 10
    foreground_color: { r: 0, g: 51, b: 102 }  # 255, 204, 0   0, 51, 102
    background_color: { r: 255, g: 255, b: 255 }
    error_correction_level: quartile # low, medium, quartile or high
    encoding: UTF-8
    label: Yne life
    label_font_size: 14   # 300 13
    label_alignment: center # left, center or right
    label_margin: { b: 20 }
    logo_path: '%kernel.root_dir%/../web/bundles/corestyle/images/ynelife/commons/logo-yne-dark@300.jpg'
    logo_width: 55    # 150 55
    validate_result: true # checks if the result is readable
```

Thank very mutch for your help.
