### ISSUE TITLE
Unable to generate a URL for the named route "qr_code_generate"

### ISSUE THREAD

**Issue by mvigneron** [endroid/qr-code-bundle#16]
Hello,

I'm testing your bundle but I have an error "Unable to generate a URL for the named route "qr_code_generate"" with Twig Extension

Symfony : 3.4
endroid/qr-code-bundle : 3.2

Config : 
```
endroid_qr_code:
  writer: 'png'
  size: 300
  margin: 10
  foreground_color: { r: 0, g: 0, b: 0 }
  background_color: { r: 255, g: 255, b: 255 }
  error_correction_level: low # low, medium, quartile or high
  encoding: UTF-8
  label: Scan the code
  label_font_size: 20
  label_alignment: left # left, center or right
  label_margin: { b: 20 }
  logo_width: 150
  validate_result: false # checks if the result is readable
```

Twig
`<div class="qrcode"><img src="{{ qr_code_url('https://www.onespot.io')}}" /></div>`

I saw the same issue on StackOverflow (https://stackoverflow.com/questions/44559897/endroid-qr-code-in-twig-in-symfony)

he says to add routing
```
EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode
```
I tested it but it doesn't work for me

Thanks
