### ISSUE TITLE
[DependencyInjection] QrCodeExtension not defined, thus not tagged as Twig extension

### ISSUE THREAD

**Issue by ghost** [endroid/qr-code-bundle#2]
As of right now, the class `QrCodeExtension` from `endroid/qrcode` is not defined as a service within this bundle, so it doesn't get tagged as a Twig extension. I'm not sure what the best way is to resolve this, but I've currently resolved it by defining it in my own application like this: 
``` YAML
Endroid\QrCode\Twig\Extension\QrCodeExtension: 
    autoconfigure: true
    autowire: true
```
