### ISSUE TITLE
symfony 4.2

### ISSUE THREAD

**Issue by gulaandrij** [endroid/qr-code-bundle#20]
When I updated to symfony v4.2.0-BETA2 I got this error
```
The service "Endroid\QrCode\Factory\QrCodeFactory" has a dependency on a non-existent service "Endroid\QrCode\Writer\BinaryWriter".
```

Can you suggest decision?

**Comment by gulaandrij** [comment]
on symfony 4.1.7 works fine

**Comment by gulaandrij** [comment]
can it be typo here? endroid.qr_code.writer => endroid_qr_code.writer

https://github.com/endroid/qr-code-bundle/blob/ebe0e82c7fc32fb5158b42b9f944c5fbcc677f87/src/Resources/config/services.yaml#L24

**Comment by gulaandrij** [comment]
ping @endroid

**Comment by endroid** [comment]
Sorry I didn't have the time yet, I'll try to look at your question asap

**Comment by endroid** [comment]
Hi @gulaandrij thank you for your question. Unfortunately I don't have SF 4.2 beta installed but the factory should not have a dependency on the binarywriter service. What version of the qr-code and qr-code-bundle do you have installed? And what does the service definition in src/Resources/config/services.yaml say?

**Comment by gulaandrij** [comment]
endroid/qr-code-bundle: 3.3.1
endroid/qr-code: 3.4.6

```yaml
endroid_qr_code:
    writer: 'png'
    size: 300
    margin: 10
    error_correction_level: 'low'
    validate_result: false
```
