### ISSUE TITLE
Route for qr_code_url not loaded as described in docs

### ISSUE THREAD

**Issue by PaddyLock** [endroid/qr-code-bundle#24]
I have seen the similar issue #16 and also tried the same as described in the docs by adding the following to my routing.yml
```
EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode
```

This also did not work for me. I looked at the bundle code and GenerateController has no route annotations.

The link to the solution in #16 goes to a 404 page, so I don't know why the issue was closed.

I am using Symfony 3.4

My solution is was add the following to the routing

```
qr_code_generate:
    path: /qr_code_url/{text}.{extension}
    requirements:
        text: "[\\w\\W]+"
    defaults:
        _controller: Endroid\QrCodeBundle\Controller\GenerateController
```

Note the addition of `/qr_code_url` to the path, otherwise any url on your website can be turned into a QR code by adding .png which could also cause error 500's if incorrect query parameters are added.

I don't know if this is the correct solution as it is undocumented, but it works for me and I hope it helps someone else.
