### ISSUE TITLE
$defaultQrCodeBuilder doesnt seems to be getting the yaml value.

### ISSUE THREAD

**Issue by Lehj14** [endroid/qr-code-bundle#49]
Hi, 

So I have the following yaml config
```
endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 20
        encoding: 'ISO-8859-1'
        errorCorrectionLevel: 'low'
        roundBlockSizeMode: 'margin'
        validateResult: false
        foregroundColor: ['0, 0, 0']
        backgroundColor: ['255, 255, 255']
```

and I inject the Builder Interface

```
public function __construct(BuilderInterface $defaultQrCodeBuilder)
{
     $this->builder = $defaultQrCodeBuilder;
}
```

then I tried to do this 

```
public function qrCode(string $data)
    {
        $result = $this->builder->data($data)
            ->build();

        header('Content-Type: '. $result->getMimeType());
        return $result->getDataUri();
    }
```

But my QR code doesn't get the right encoding. When I add `->encoding(new Encoding('ISO-8859-1'))` it gives the right result, am i doing something wrong above?
