### ISSUE TITLE
Add a configuration setting to not load/create `config/routes/endroid_qr_code.yaml`

### ISSUE THREAD

**Issue by maks-rafalko** [endroid/qr-code-bundle#52]
In our application, we don't need the default rout to be exposed, but each time we delete  `config/routes/endroid_qr_code.yaml` it is created automatically.

Can we have a setting or somehow prevent the system from creating it?

**Comment by mssimi** [comment]
I face similar problem. I have already migrated to php config, coz https://github.com/symfony/symfony/issues/37186

But still yaml config is recreated.

**Comment by maks-rafalko** [comment]
Ok, solved it using https://github.com/endroid/installer's configuration, in particular:

`composer.json`

```json
{
    "extra": {
        "endroid": {
            "installer": {
                "enabled": true,
                "exclude": [
                    "endroid/qr-code-bundle"
                ]
            }
        }
    }
}
```

**Comment by endroid** [comment]
The files should only be created upon installation, not on update so I think that is a bug. I will look at that. Still I think it is useful to mention this in the docs so I will create a reference to the endroid/install section on disabling auto-configuration. Thank you!

**Comment by rejmann** [comment]
I can disable the creation of files as follows...
```json
{
"config": {
        "allow-plugins": {
            "endroid/installer": false,
    }
}
```

or with the commands below:

`composer config --no-plugins allow-plugins.endroid/installer false`

This way it will be necessary to create the `endroid_qr_code.yaml` file inside `config/packages/endroid_qr_code.yaml` and set the settings below:
```yml
endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 300
        margin: 10
        encoding: 'UTF-8'
        errorCorrectionLevel: 'low'
        roundBlockSizeMode: 'margin'
        validateResult: false

```
