### ISSUE TITLE
Keep a BC v1.x branch

### ISSUE THREAD

**Issue by davidromani** [endroid/qr-code-bundle#9]
Due to your git tag changes, it's impossible to keep a deprecated version (1.x) of your bundle inside a SF2 (legacy) project.

I can't upgrade to SF3, and I can't install this composer.json:
```bash
{
    "require": {
        "endroid/qrcode-bundle": "^1.0",
        (...)
```
Because these problems:
```bash
$ composer install
  - Installing endroid/qrcode (1.9.3): Loading from cache
  - Installing endroid/qrcode-bundle (1.6.6): Downloading (0%)    Failed to download endroid/qrcode-bundle from dist: The "https://codeload.github.com/endroid/qr-code-bundle/legacy.zip/f8f12fd9f6414a98e21b85acac4859d40b70130e" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing endroid/qrcode-bundle (1.6.6): Cloning f8f12fd9f6 from cache
    f8f12fd9f6414a98e21b85acac4859d40b70130e is gone (history was rewritten?)
```
```bash
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package endroid/qrcode-bundle ^1.0 exists as endroid/qrcode-bundle[3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1, dev-master, 3.x-dev] but these are rejected by your constraint.
```

What can I do to solve it? Thx.

**Comment by endroid** [comment]
Hi @davidromani thank you for your question. In later versions of 1.x and throughout 2.x the bundle can be found inside the endroid/qr-code library. So you can install that library and register the bundle found there in your kernel. Please let me know if both are incompatible with your project. If your project is really too old maybe we can make a change on the 1.x or 2.x branch to make it work.

FYI: the old endroid/qrcode-bundle was abandoned a year ago and removed half a year ago. The bundle was re-introduced in 3.x mainly to take advantage of Symfony Flex. In the meanwhile I also created a [code sanctuary](https://github.com/abandroid) to handle such cases in the future and make sure old tags are not lost when cleaning up my account.

**Comment by davidromani** [comment]
Thx @endroid but still not working, now I have a new problem. Check my steps:

1. I've replaced `"endroid/qrcode-bundle": "^1.0"` by `"endroid/qr-code": "^1.0"` in composer.json
2. I've executed a composer update with this result:

```bash
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 2 updates, 1 removal
  - Removing endroid/qrcode (1.9.3)
  - Installing endroid/qr-code (1.9.3): Downloading (100%)         
Writing lock file
```

3. I've replaced `Endroid\Bundle\QrCodeBundle\EndroidQrCodeBundle()` by `Endroid\QrCode\Bundle\EndroidQrCodeBundle()` in AppKernel.php

And now I'm getting this error 500 `The parameter "endroid_qrcode.extension" must be defined`. My configuration doesn't change, is the same, and it looks like this:

```yaml
# app/config/config.yml
endroid_qr_code:
    size:                   "%qr_code_size%"
    padding:                "%qr_code_padding%"
    extension:              "%qr_code_extension%"
    error_correction_level: "%qr_code_error_correction_level%"
    foreground_color:       "%qr_code_foreground%"
    background_color:       "%qr_code_background%"
```
